server:
  port: 8765

# sidecar:
#   port: 8000
#
# endpoints:
#   restart:
#     enabled: true
#   shutdown:
#     enabled: true
#   health:
#     sensitive: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
